forum_modules/books/urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _

import views as app

urlpatterns = patterns('',
    url(r'^%s$' % _('books/'), app.books, name='books'),
    url(r'^%s%s(?P<short_name>[^/]+)/$' % (_('books/'), _('ask/')), app.ask_book, name='ask_book'),
    url(r'^%s(?P<short_name>[^/]+)/$' % _('books/'), app.book, name='book'),
)

forum_modules/facebookauth/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from views import user_is_registered

urlpatterns = patterns('',
    url(r'^xd_receiver.htm$',  direct_to_template,  {'template': 'modules/facebookauth/xd_receiver.html'}, name='xd_receiver'),
    url(r'^facebook/user_is_registered/', user_is_registered, name="facebook_user_is_registered"),
)

forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'^%s' % settings.FORUM_SCRIPT_ALIAS, include('forum.urls')),
)

forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

question_view = django.dispatch.Signal(providing_args=['instance', 'user'])

class Question(QandA):
    accepted_answer = models.OneToOneField('Answer', null=True, related_name="question_accepting")
    closed          = models.BooleanField(default=False)
    closed_by       = models.ForeignKey(User, null=True, blank=True, related_name='closed_questions')
    closed_at       = models.DateTimeField(null=True, blank=True)
    close_reason    = models.SmallIntegerField(choices=CLOSE_REASONS, null=True, blank=True)
    subscribers     = models.ManyToManyField(User, related_name='subscriptions', through='QuestionSubscription')

    # Denormalised data
    answer_count         = models.PositiveIntegerField(default=0)
    view_count           = models.IntegerField(default=0)
    favourite_count      = models.IntegerField(default=0)
    last_activity_at     = models.DateTimeField(default=datetime.datetime.now)
    last_activity_by     = models.ForeignKey(User, related_name='last_active_in_questions', null=True)

    favorited_by         = models.ManyToManyField(User, through='FavoriteQuestion', related_name='favorite_questions')

    class Meta(QandA.Meta):
        db_table = u'question'

    @property
    def headline(self):
        if self.closed:
            return _('[closed] ') + self.title

        if self.deleted:
            return _('[deleted] ') + self.title

        return self.title

    @property
    def answer_accepted(self):
        return self.accepted_answer is not None

    def save(self, *args, **kwargs):
        if not self.last_activity_by:
            self.last_activity_by = self.author
        super(Question, self).save(*args, **kwargs)

    def update_last_activity(self, user):
        self.last_activity_by = user
        self.last_activity_at = datetime.datetime.now()
        self.save()

    def activate_revision(self, user, revision):
        super(Question, self).activate_revision(user, revision)
        self.update_last_activity(user)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})

    def get_answer_count_by_user(self, user_id):
        from answer import Answer
        query_set = Answer.objects.filter(author__id=user_id)
        return query_set.filter(question=self).count()

    def get_question_title(self):
        if self.closed:
            attr = CONST['closed']
        elif self.deleted:
            attr = CONST['deleted']
        else:
            attr = None
        if attr is not None:
            return u'%s %s' % (self.title, attr)
        else:
            return self.title

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).exclude(deleted=True).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]

    def __unicode__(self):
        return self.title

def question_viewed(instance, **kwargs):
    instance.view_count += 1
    instance.save()

question_view.connect(question_viewed)

class FavoriteQuestion(models.Model):
    question      = models.ForeignKey('Question')
    user          = models.ForeignKey(User, related_name='user_favorite_questions')
    added_at      = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        unique_together = ('question', 'user')
        app_label = 'forum'
        db_table = u'favorite_question'

    def __unicode__(self):
        return '[%s] favorited at %s' %(self.user, self.added_at)

    def _update_question_fav_count(self, diff):
        self.question.favourite_count = self.question.favourite_count + diff
        self.question.save()

    def save(self, *args, **kwargs):
        super(FavoriteQuestion, self).save(*args, **kwargs)
        if self._is_new:
            self._update_question_fav_count(1)

    def delete(self):
        self._update_question_fav_count(-1)
        super(FavoriteQuestion, self).delete()

class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

forum/models/tag.py
from base import *

from django.utils.translation import ugettext as _
import django.dispatch

class ActiveTagManager(UndeletedObjectManager):
    def get_query_set(self):
        return super(UndeletedObjectManager, self).get_query_set().exclude(used_count=0)


class Tag(BaseModel, DeletableContent):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    objects = models.Manager()
    active = ActiveTagManager()

    class Meta(DeletableContent.Meta):
        db_table = u'tag'
        ordering = ('-used_count', 'name')

    def __unicode__(self):
        return self.name

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good',_('interesting')),('bad',_('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

forum/views/users.py
from django.contrib.auth.decorators import login_required
from forum.models import User
from django.db.models import Q, Count
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.template.defaultfilters import slugify
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect, Http404
from django.utils.translation import ugettext as _
from django.utils.http import urlquote_plus
from django.utils.html import strip_tags
from django.utils import simplejson
from django.core.urlresolvers import reverse
from forum.forms import *
from forum.utils.html import sanitize_html
from forum.authentication import user_updated
import decorators

import time

USERS_PAGE_SIZE = 35# refactor - move to some constants file

def users(request):
    is_paginated = True
    sortby = request.GET.get('sort', 'reputation')
    suser = request.REQUEST.get('q',  "")
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    if suser == "":
        if sortby == "newest":
            objects_list = Paginator(User.objects.all().order_by('-date_joined'), USERS_PAGE_SIZE)
        elif sortby == "last":
            objects_list = Paginator(User.objects.all().order_by('date_joined'), USERS_PAGE_SIZE)
        elif sortby == "user":
            objects_list = Paginator(User.objects.all().order_by('username'), USERS_PAGE_SIZE)
        # default
        else:
            objects_list = Paginator(User.objects.all().order_by('-reputation'), USERS_PAGE_SIZE)
        base_url = reverse('users') + '?sort=%s&' % sortby
    else:
        sortby = "reputation"
        objects_list = Paginator(User.objects.filter(username__icontains=suser).order_by('-reputation'), USERS_PAGE_SIZE)
        base_url = reverse('users') + '?name=%s&sort=%s&' % (suser, sortby)

    try:
        users = objects_list.page(page)
    except (EmptyPage, InvalidPage):
        users = objects_list.page(objects_list.num_pages)

    return render_to_response('users/users.html', {
                                "users" : users,
                                "suser" : suser,
                                "keywords" : suser,
                                "tab_id" : sortby,
                                "context" : {
                                    'is_paginated' : is_paginated,
                                    'pages': objects_list.num_pages,
                                    'page': page,
                                    'has_previous': users.has_previous(),
                                    'has_next': users.has_next(),
                                    'previous': users.previous_page_number(),
                                    'next': users.next_page_number(),
                                    'base_url' : base_url
                                }

                                }, context_instance=RequestContext(request))

@login_required
def moderate_user(request, id):
    """ajax handler of user moderation
    """
    if not request.user.is_superuser or request.method != 'POST':
        raise Http404
    if not request.is_ajax():
        return HttpResponseForbidden(mimetype="application/json")

    user = get_object_or_404(User, id=id)
    form = ModerateUserForm(request.POST, instance=user)

    if form.is_valid():
        form.save()
        logging.debug('data saved')
        response = HttpResponse(simplejson.dumps(''), mimetype="application/json")
    else:
        response = HttpResponseForbidden(mimetype="application/json")
    return response

def set_new_email(user, new_email, nomessage=False):
    if new_email != user.email:
        user.email = new_email
        user.email_isvalid = False
        user.save()
        #if settings.EMAIL_VALIDATION == 'on':
        #    send_new_email_key(user,nomessage=nomessage)    

@login_required
def edit_user(request, id):
    user = get_object_or_404(User, id=id)
    if request.user != user:
        raise Http404
    if request.method == "POST":
        form = EditUserForm(user, request.POST)
        if form.is_valid():
            new_email = sanitize_html(form.cleaned_data['email'])

            set_new_email(user, new_email)

            #user.username = sanitize_html(form.cleaned_data['username'])
            user.real_name = sanitize_html(form.cleaned_data['realname'])
            user.website = sanitize_html(form.cleaned_data['website'])
            user.location = sanitize_html(form.cleaned_data['city'])
            user.date_of_birth = sanitize_html(form.cleaned_data['birthday'])
            if len(user.date_of_birth) == 0:
                user.date_of_birth = '1900-01-01'
            user.about = sanitize_html(form.cleaned_data['about'])

            user.save()
            # send user updated signal if full fields have been updated
            if user.email and user.real_name and user.website and user.location and \
                user.date_of_birth and user.about:
                user_updated.send(sender=user.__class__, instance=user, updated_by=user)
            return HttpResponseRedirect(user.get_profile_url())
    else:
        form = EditUserForm(user)
    return render_to_response('users/edit.html', {
                                                'form' : form,
                                                'gravatar_faq_url' : reverse('faq') + '#gravatar',
                                    }, context_instance=RequestContext(request))



def user_view(template, tab_name, tab_description, page_title):
    def decorator(fn):
        def decorated(request, id, slug=None):
            context = fn(request, get_object_or_404(User, id=id))
            context.update({
                "tab_name" : tab_name,
                "tab_description" : tab_description,
                "page_title" : page_title,
            })
            return render_to_response(template, context, context_instance=RequestContext(request))
        return decorated
    return decorator


@user_view('users/stats.html', 'stats', _('user profile'), _('user profile overview'))
def user_stats(request, user):
    questions = Question.objects.filter(author=user, deleted=False).order_by('-added_at')
    answers = Answer.objects.filter(author=user, deleted=False).order_by('-added_at')

    up_votes = user.get_up_vote_count()
    down_votes = user.get_down_vote_count()
    votes_today = user.get_vote_count_today()
    votes_total = int(settings.MAX_VOTES_PER_DAY)

    user_tags = Tag.objects.filter(Q(nodes__author=user) | Q(nodes__children__author=user)) \
        .annotate(user_tag_usage_count=Count('name')).order_by('-user_tag_usage_count')

    awards = Badge.objects.filter(award_badge__user=user).annotate(count=Count('name')).order_by('-count')

    if request.user.is_superuser:
        moderate_user_form = ModerateUserForm(instance=user)
    else:
        moderate_user_form = None

    return {'moderate_user_form': moderate_user_form,
            "view_user" : user,
            "questions" : questions,
            "answers" : answers,
            "up_votes" : up_votes,
            "down_votes" : down_votes,
            "total_votes": up_votes + down_votes,
            "votes_today_left": votes_total-votes_today,
            "votes_total_per_day": votes_total,
            "user_tags" : user_tags[:50],
            "awards": awards,
            "total_awards" : awards.count(),
        }

@user_view('users/recent.html', 'recent', _('recent user activity'), _('profile - recent activity'))
def user_recent(request, user):
    activities = Activity.objects.filter(activity_type__in=(TYPE_ACTIVITY_PRIZE,
            TYPE_ACTIVITY_ASK_QUESTION, TYPE_ACTIVITY_ANSWER,
            TYPE_ACTIVITY_COMMENT_QUESTION, TYPE_ACTIVITY_COMMENT_ANSWER,
            TYPE_ACTIVITY_MARK_ANSWER), user=user).order_by('-active_at')[:USERS_PAGE_SIZE]

    return {"view_user" : user, "activities" : activities}


@user_view('users/votes.html', 'votes', _('user vote record'), _('profile - votes'))
def user_votes(request, user):
    votes = user.votes.exclude(node__deleted=True).order_by('-voted_at')[:USERS_PAGE_SIZE]

    return {"view_user" : user, "votes" : votes}


@user_view('users/reputation.html', 'reputation', _('user reputation in the community'), _('profile - user reputation'))
def user_reputation(request, user):
    reputation = user.reputes.order_by('-reputed_at')

    graph_data = simplejson.dumps([
            (time.mktime(rep.reputed_at.timetuple()) * 1000, rep.reputation)
            for rep in reputation
    ])

    return {"view_user": user, "reputation": reputation, "graph_data": graph_data}

@user_view('users/questions.html', 'favorites', _('favorite questions'),  _('profile - favorite questions'))
def user_favorites(request, user):
    questions = user.favorite_questions.filter(deleted=False)

    return {"questions" : questions, "view_user" : user}

@user_view('users/subscriptions.html', 'subscriptions', _('subscription settings'), _('profile - subscriptions'))
def user_subscriptions(request, user):
    if request.method == 'POST':
        form = SubscriptionSettingsForm(request.POST)

        if 'notswitch' in request.POST:
            user.subscription_settings.enable_notifications = not user.subscription_settings.enable_notifications
            user.subscription_settings.save()

            if user.subscription_settings.enable_notifications:
                request.user.message_set.create(message=_('Notifications are now enabled'))
            else:
                request.user.message_set.create(message=_('Notifications are now disabled'))
        else:
            form.is_valid()
            for k,v in form.cleaned_data.items():
                setattr(user.subscription_settings, k, v)

forum/skins/default/templates/account_settings.html
{% extends "base_content.html" %}
<!-- settings.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Account functions" %}{% endspaceless %}{% endblock %}
{% block head %}
<style type="text/css" media="screen">
    h4 {font-size:12pt;}
	dt, dd { padding:0 0 0.35em 0; }
	dt { float: left; width: 21ex;  }
	dd { margin-left: 23ex;  }
	
	#settings-options, #settings-intro { padding: 4em 1.5em;}
	#settings-options { min-height: 300px; border-left: 1px solid #333;}
	
	#settings-options h5 { font-weight: bold;}
</style>
{% endblock %}

{% block content %}
<div id="main-bar">
    <h3><strong>{{ request.user.username }} {% trans "Profile" %}</strong></h3>
</div>
<div id="settings-options">
	{% if msg %}
		<p class="error">{{ msg }}</p>
	{% endif %}

	<dl class="list-item">
        <dt>» <a href="{% url user_changepw %}">{% trans "Change password" %}</a></dt>
        <dd>{% trans "Give your  account a new password." %}</dd>
        {% comment %}
        <dt>» <a href="{% url user_changeemail %}">{% trans "Change email " %}</a></dt>
        <dd>{% trans "Add or update the email address associated with your account." %}</dd>

        <dt>» <a href="{% url user_changeopenid %}">{% trans "Change OpenID" %}</a></dt>
        <dd>{% trans "Change openid associated to your account" %}</dd>

        
        <dt>» <a href="{% url user_delete %}">{% trans "Delete account" %}</a></dt>
        <dd>{% trans "Erase your username and all your data from website" %}</dd>
        {% endcomment %}
	</dl>
</div>
{% endblock %}
<!-- end settings.html -->

forum/skins/default/templates/edit_user_email_feeds_form.html
{% load i18n %}
<table class='form-as-table'>
{{email_feeds_form.as_table}}
</table>

forum/skins/default/templates/question.html
{% extends "base.html" %}
<!-- question.html -->
{% load node_tags %}
{% load extra_tags %}
{% load extra_filters %}
{% load smart_if %}
{% load humanize %}
{% load i18n %}
{% load cache %}
{% block title %}{% spaceless %}{{ question.get_question_title }}{% endspaceless %}{% endblock %}
{% block forejs %}
        <meta name="description" content="{{question.summary}}" />
        <meta name="keywords" content="{{question.tagname_meta_generator}}" />
        <link rel="canonical" href="{{settings.APP_URL}}{{question.get_absolute_url}}" />
        {% if not question.closed %}
        <script type='text/javascript' src='{% media  "/media/js/wmd/showdown.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/wmd/wmd.js" %}'></script>
        <link rel="stylesheet" type="text/css" href="{% media  "/media/js/wmd/wmd.css" %}" />
        {% endif %}

        <script type="text/javascript">
        // define reputation needs for comments
        var repNeededForComments = 50;
        $().ready(function(){
            $("#nav_questions").attr('className',"on");
            var answer_sort_tab = "{{ tab_id }}";
            $("#" + answer_sort_tab).attr('className',"on");

            $('#editor').TextAreaResizer();
        });
        </script>
        <noscript>
            <style>
                .comment.not_top_scorer {
                    display: block;
                }
                .comment-form-container {
                    display: block;
                }
                .div.comment-tools {
                    display: none;
                }
            </style>
        </noscript>
{% endblock %}
        
{% block content %}
<div class="headNormal">
    <a href="{{ question.get_absolute_url }}">{{ question.get_question_title }}</a>
</div>
<div id="main-body" class="">
    <div id="askform">
            <table style="width:100%;" id="question-table" {% if question.deleted %}class="deleted"{%endif%}>
                <tr>
                    <td style="width:30px;vertical-align:top">
                        <div class="vote-buttons">
                            {% vote_buttons question request.user %}
                            {% favorite_mark question request.user %}                            
                        </div>
                    </td>
                    <td>
                        <div id="item-right">
                            <div class="question-body">
                                {{ question.html|safe }}
                            </div>
                            <div id="question-controls" class="post-controls">
                                <div id="question-tags" class="tags">
                                    {% for tag in question.tagname_list %}
                                        <a href="{% url tag_questions tag|urlencode %}" class="post-tag"
                                            title="{% blocktrans with tag as tagname %}see questions tagged '{{ tagname }}'{% endblocktrans %}" rel="tag">{{ tag }}</a>
                                    {% endfor %}
                                </div>
                                {% post_controls question request.user %}
                            </div>
                            <div class="post-update-info-container">
                                    {% post_contributor_info question "original_author" %}
                                    {% post_contributor_info question "last_updater" %}
                            </div>
                            {% comments question request.user %}
                        </div>
                        
                    </td>
                </tr>
            </table>
            {% if question.closed %}
            <div class="question-status" style="margin-bottom:15px">
            <h3>{% blocktrans with question.get_close_reason_display as close_reason %}The question has been closed for the following reason "{{ close_reason }}" by{% endblocktrans %} 
            <a href="{{ question.closed_by.get_profile_url }}">{{ question.closed_by.username }}</a> 
            {% blocktrans with question.closed_at as closed_at %}close date {{closed_at}}{% endblocktrans %}</h3>
            </div>
            {% endif %}
            {% if answers %}
                <hr/>
                <div class="tabBar">
                    <a name="sort-top"></a>
                    <div class="headQuestions">
                    {% blocktrans count answers|length as counter %}
                    One Answer:
                    {% plural %}
                    {{counter}} Answers:
                    {% endblocktrans %}
                    </div>
                    <div class="tabsA">
                         <a id="oldest" href="{{ question.get_absolute_url }}?sort=oldest#sort-top"
                            title="{% trans "oldest answers will be shown first" %}">{% trans "oldest answers" %}</a>
                        <a id="latest" href="{{ question.get_absolute_url }}?sort=latest#sort-top"
                            title="{% trans "newest answers will be shown first" %}">{% trans "newest answers" %}</a>
                        <a id="votes" href="{{ question.get_absolute_url }}?sort=votes#sort-top" 
                            title="{% trans "most voted answers will be shown first" %}">{% trans "popular answers" %}</a>   
                    </div>
                </div>
                {% cnprog_paginator context %}
  
                {% for answer in answers %}
                    <a name="{{ answer.id }}"></a>
                    <div id="answer-container-{{ answer.id }}" class="answer {% if answer.accepted %}accepted-answer{% endif %} {% ifequal answer.author_id question.author_id %} answered-by-owner{% endifequal %} {% if answer.deleted %}deleted{% endif %}">
                        <table style="width:100%;">
                            <tr>
                                <td style="width:30px;vertical-align:top">
                                    <div class="vote-buttons">
                                        {% vote_buttons answer request.user %}
                                        {% accept_button answer request.user %}
                                    </div>
                                </td>
                                <td>
                                    <div class="item-right">
                                        <div class="answer-body">
                                            {{ answer.html|safe }}
                                        </div>
                                        <div class="answer-controls post-controls">
                                            {% post_controls answer request.user %}
                                        </div>
                                        <div class="post-update-info-container">
                                                {% post_contributor_info answer "original_author" %}
                                                {% post_contributor_info answer "last_updater" %}
                                        </div>
                                        {% comments answer request.user %}
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                {% endfor %}
                <div class="paginator-container-left">
                    {% cnprog_paginator context %}
                </div>
            {% endif %}
        <form id="fmanswer" action="{% url answer question.id %}" method="post">
            <div style="clear:both">
            </div>
            
            {% if not question.closed %}
                <div style="padding:10px 0 0 0;">
                    {% spaceless %}
                    <div class="headNormal">
                        {% if answers %}
                            {% trans "Your answer" %}
                        {% else %}
                            {% trans "Be the first one to answer this question!" %}
                        {% endif %}
                    </div>
                    {% endspaceless %}
                </div>
                {% if not request.user.is_authenticated %}
                    <div class="message">{% trans "you can answer anonymously and then login" %}</div>
                {% else %}
                    <p class="message">
                        {% ifequal request.user question.author  %}
                            {% trans "answer your own question only to give an answer" %}
                        {% else %}
                            {% trans "please only give an answer, no discussions" %}
                        {% endifequal %}
                    </p>
                {% endif %}

                <div id="description" class="" >
                    <div id="wmd-button-bar" class="wmd-panel"></div>
                    {{ answer.text }}
                    <div class="preview-toggle">
                        <table width="100%">
                            <tr>
                                <td>
                                    <span id="pre-collapse" 
                                        title="{% trans "Toggle the real time Markdown editor preview" %}">
                                            {% trans "toggle preview" %}
                                    </span>
                                </td>
                                {% if settings.WIKI_ON %}
                                <td style="text-align:right;">
                                    {{ answer.wiki }} 
                                    <span style="font-weight:normal;cursor:help" 
                                        title="{{answer.wiki.help_text}}">
                                            {{ answer.wiki.label_tag }} 
                                    </span>
                                </td>
                                {% endif %}
                            </tr>
                        
                        </table>  
                    </div>
                    <div id="previewer" class="wmd-preview"></div>
                    {{ answer.text.errors }}
                </div>
                <p><span class="form-error"></span></p>
                <input type="submit" 
                    {% if user.is_anonymous %}
                        value="{% trans "Login/Signup to Post Your Answer" %}" 
                    {% else %}
                        {% if user == question.author %}
                        value="{% trans "Answer Your Own Question" %}" 
                        {% else %}
                        value="{% trans "Answer the question" %}" 
                        {% endif %}
                    {% endif %}
                    class="submit" style="float:left"/>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
<div class="boxC" id="subscription_box">
    {% include "subscription_status.html" %}
</div>
{% cache 60 questions_tags settings.APP_URL question.id %}
<div class="boxC">
    <p>
		{% trans "Question tags" %}:
    </p>
    <p class="tags" >
        {% for tag in tags %}
        	<a href="{% url tag_questions tag.name|urlencode %}" 
			title="{% trans "see questions tagged"%}'{{tag.name}}'{% trans "using tags" %}" 
			rel="tag">{{ tag.name }}</a> <span class="tag-number">&#215;{{ tag.used_count|intcomma }}</span><br/>
        {% endfor %}
    </p>
    <p>
        {% trans "question asked" %}: <strong title="{{ question.added_at }}">{% diff_date question.added_at %}</strong>
    </p>
    <p> 
     	{% trans "question was seen" %}: <strong>{{ question.view_count|intcomma }} {% trans "times" %}</strong>
    </p>
    <p> 
        {% trans "last updated" %}: <strong title="{{ question.last_activity_at }}">{% diff_date question.last_activity_at %}</strong>
    </p>
</div>
{% endcache %}
<div class="boxC">
    <h3 class="subtitle">{% trans "Related questions" %}</h3>
    <div class="questions-related">

        {% for question in similar_questions %}
        <p>
            <a href="{{ question.get_absolute_url }}">{{ question.get_question_title }}</a>
        </p>
        {% endfor %}

    </div>
</div>

{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end question.html -->

forum/skins/default/templates/user_favorites.html
{% extends "user.html" %}
<!-- user_favorites.html -->
{% load extra_tags %}
{% load humanize %}
{% block usercontent %}
		{% include "users_questions.html" %}
{% endblock %}
<!-- end user_favorites.html -->